spring.application.name=techstore

spring.jpa.hibernate.ddl-auto=validate

spring.security.user.name=admin
spring.security.user.password=123456789

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=accvipsc1@gmail.com
spring.mail.password=ybvoixomnogwcgxi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.file.name=logs/app.log